/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * singbox-tauri
 * A Tauri client for sing-box
 * OpenAPI spec version: 0.1.0
 */
import { localApiRequest } from './http';
export interface AppEventAccepted {
  ok: boolean;
}

export interface AppEventRequest {
  message: string;
}

export type AppLifecycle = typeof AppLifecycle[keyof typeof AppLifecycle];


export const AppLifecycle = {
  stopped: 'stopped',
  starting: 'starting',
  runningPassive: 'runningPassive',
  runningSelective: 'runningSelective',
  runningFull: 'runningFull',
  stopping: 'stopping',
} as const;

export type AppRunMode = typeof AppRunMode[keyof typeof AppRunMode];


export const AppRunMode = {
  passive: 'passive',
  selective: 'selective',
  full: 'full',
} as const;

export interface SingboxCheck {
  detail: string;
  name: string;
  ok: boolean;
}

export type ProcessStatus = typeof ProcessStatus[keyof typeof ProcessStatus];


export const ProcessStatus = {
  stopped: 'stopped',
  starting: 'starting',
  running: 'running',
  stopping: 'stopping',
} as const;

export interface SingboxBootstrapReport {
  binaryPath: string;
  checks: SingboxCheck[];
  logPath: string;
  pidPath: string;
  processStatus: ProcessStatus;
  sessionPath: string;
  /** @nullable */
  version?: string | null;
}

export type RuntimeMode = typeof RuntimeMode[keyof typeof RuntimeMode];


export const RuntimeMode = {
  envOverride: 'envOverride',
  dev: 'dev',
  production: 'production',
} as const;

export interface RuntimePaths {
  binDir: string;
  configDir: string;
  logsDir: string;
  mode: RuntimeMode;
  root: string;
  secretsDir: string;
  stateDir: string;
  subscriptionsDir: string;
}

export interface SingboxRuntimeStatus {
  binaryPath: string;
  configPath: string;
  lifecycle: AppLifecycle;
  logPath: string;
  mode: AppRunMode;
  /**
   * @minimum 0
   * @nullable
   */
  pid?: number | null;
  pidPath: string;
  processStatus: ProcessStatus;
  sessionPath: string;
  /** @nullable */
  version?: string | null;
}

export type SubscriptionKeyState = typeof SubscriptionKeyState[keyof typeof SubscriptionKeyState];


export const SubscriptionKeyState = {
  missing: 'missing',
  ready: 'ready',
} as const;

export type SubscriptionFetchState = typeof SubscriptionFetchState[keyof typeof SubscriptionFetchState];


export const SubscriptionFetchState = {
  idle: 'idle',
  fetched: 'fetched',
  failed: 'failed',
} as const;

export type SubscriptionDecryptState = typeof SubscriptionDecryptState[keyof typeof SubscriptionDecryptState];


export const SubscriptionDecryptState = {
  idle: 'idle',
  ready: 'ready',
  failed: 'failed',
} as const;

export interface SubscriptionSnapshot {
  activeConfigPath: string;
  decryptState: SubscriptionDecryptState;
  decryptedPath: string;
  encryptedPath: string;
  fetchState: SubscriptionFetchState;
  keyState: SubscriptionKeyState;
  lastError?: string | null;
  privateKeyPath: string;
  publicKey?: string | null;
  publicKeyPath: string;
  sourceUrl?: string | null;
}

export interface ControlSnapshotResponse {
  app_log: string;
  bootstrap: SingboxBootstrapReport;
  runtime: RuntimePaths;
  runtime_metadata: string;
  session_raw: string;
  singbox_log: string;
  status: SingboxRuntimeStatus;
  subscription: SubscriptionSnapshot;
  tab: string;
}

export interface ControlStateResponse {
  bootstrap: SingboxBootstrapReport;
  runtime: RuntimePaths;
  status: SingboxRuntimeStatus;
  subscription: SubscriptionSnapshot;
}

export interface HealthResponse {
  ok: boolean;
}

export const getSingboxTauri = () => {
const appendEvent = (
    appEventRequest: AppEventRequest,
 ) => {
      return localApiRequest<AppEventAccepted>(
      {url: `/api/v1/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: appEventRequest
    },
      );
    }
  
const health = (
    
 ) => {
      return localApiRequest<HealthResponse>(
      {url: `/api/v1/health`, method: 'GET'
    },
      );
    }
  
const appLog = (
    
 ) => {
      return localApiRequest<string>(
      {url: `/api/v1/logs/app`, method: 'GET'
    },
      );
    }
  
const singboxLog = (
    
 ) => {
      return localApiRequest<string>(
      {url: `/api/v1/logs/singbox`, method: 'GET'
    },
      );
    }
  
const restart = (
    
 ) => {
      return localApiRequest<SingboxRuntimeStatus>(
      {url: `/api/v1/restart`, method: 'POST'
    },
      );
    }
  
const snapshot = (
    
 ) => {
      return localApiRequest<ControlSnapshotResponse>(
      {url: `/api/v1/snapshot`, method: 'GET'
    },
      );
    }
  
const start = (
    
 ) => {
      return localApiRequest<SingboxRuntimeStatus>(
      {url: `/api/v1/start`, method: 'POST'
    },
      );
    }
  
const state = (
    
 ) => {
      return localApiRequest<ControlStateResponse>(
      {url: `/api/v1/state`, method: 'GET'
    },
      );
    }
  
const stop = (
    
 ) => {
      return localApiRequest<SingboxRuntimeStatus>(
      {url: `/api/v1/stop`, method: 'POST'
    },
      );
    }
  
return {appendEvent,health,appLog,singboxLog,restart,snapshot,start,state,stop}};
export type AppendEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSingboxTauri>['appendEvent']>>>
export type HealthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSingboxTauri>['health']>>>
export type AppLogResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSingboxTauri>['appLog']>>>
export type SingboxLogResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSingboxTauri>['singboxLog']>>>
export type RestartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSingboxTauri>['restart']>>>
export type SnapshotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSingboxTauri>['snapshot']>>>
export type StartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSingboxTauri>['start']>>>
export type StateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSingboxTauri>['state']>>>
export type StopResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSingboxTauri>['stop']>>>
